version: '3.8'
services:
  app:
    build: .
    volumes:
      - path/to/database.aka:/database/database.aka
    environment:
      - DATABASE_PATH=/database/database.aka
    ports:
      - "9900:8080"
